version: '3'

services:
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    env_file: .env
    environment:
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    

    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db-init/:/docker-entrypoint-initdb.d
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - DB_USERNAME=$MONGO_USERNAME
      - DB_PASSWORD=$MONGO_PASSWORD
      - DB_HOSTNAME=db
      - DB_PORT=$MONGO_PORT
      - DB_DB=$MONGO_DB
    ports:
      - "3000:3000"
    volumes:
      - .:/root/Documentos/WebApp/WebApp/
      - node_modules:/root/Documentos/WebApp/WebApp/node_modules
    networks:
      - app-network
    


 
networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
  mysql-data:  