version: '3.7'

services:


  nodefe:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
    - nodeusu
   
    #  image: nodejs
    container_name: nodefe
    restart: always
    # env_file: .env
    ports:
      - '3000:3000'

      #    volumes:
      #- .:/root/Documentos/WebApp/WebApp/
      #- node_modules:/root/Documentos/WebApp/WebApp/node_modules/
    networks:
      - app-network
 



  nodeusu:
    build:
      context: ./../usuarios/ORTCA-Usuarios
      dockerfile: Dockerfile
    depends_on:
      - db
    #  image: nodejs
    container_name: nodeUsu
    restart: always
    # env_file: .env
    ports:
      - '3001:3001'

      #     volumes:
      #- .:/root/Documentos/WebApp/WebApp/
      #- node_modules:/root/Documentos/WebApp/WebApp/node_modules/
    networks:
      - app-network-usuarios





  db:
    container_name: mysql
    image: mysql
    restart: always
    env_file: .env
    environment:
      - MYSQL_USER={$MYSQL_USER}
      - MYSQL_PASSWORD={$MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD={$MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE={$MYSQL_DATABASE}
    
    

    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db-init/:/docker-entrypoint-initdb.d







networks:
  app-network:
    driver: bridge
  app-network-usuarios:
    driver: bridge

volumes:
  dbdata:
  node_modules:
  mysql-data:  
